SCENARIOS_CODEX = [
    {
        # Adversarial review (Codex, gpt-5.6-sol via orca-cli /review) caught this:
        # spcl_cnd="해당무" is not an absent field, it's evidence explicitly stating
        # no preferential condition applies -- that's a direct conflict with the
        # claim, not "정보 자체가 없음" per CLAUDE.md's INSUFFICIENT definition.
        # Originally labeled INSUFFICIENT/missing_information; corrected to
        # UNSUPPORTED/fabricated_condition after review.
        "claim_id": "p025_c01",
        "product_id": "p025",
        "source_field": "spcl_cnd",
        "label": "UNSUPPORTED",
        "error_type": "fabricated_condition",
        "error_match": ["급여이체 실적"],
        "reasoning_type": [],
        "insufficient_source": None,
        "instruction": "spcl_cnd가 '해당무'(우대조건 명시적으로 없음)인데, 급여이체 실적을 충족하면 우대금리를 받는다고 그럴듯하게 주장 -- 정보 부재가 아니라 evidence의 명시적 부정과 직접 충돌.",
        "answer_text": "KB Star 정기예금은 급여이체 실적을 충족하면 연 0.2%p의 우대금리를 받을 수 있다.",
        "claims": ["KB Star 정기예금은 급여이체 실적을 충족하면 연 0.2%p의 우대금리를 받을 수 있다."],
        "author": "codex",
    },
    {
        "claim_id": "p028_c01",
        "product_id": "p028",
        "source_field": "spcl_cnd",
        "label": "SUPPORTED",
        "error_type": None,
        "error_match": [],
        "reasoning_type": ["temporal_scope"],
        "insufficient_source": None,
        "instruction": "4회전기간부터 트리플 회전 우대이율 0.1%p가 적용된다는 조건을 그대로 서술.",
        "answer_text": "NH왈츠회전예금 II는 4회전기간부터 트리플 회전 우대이율 0.1%p가 적용된다.",
        "claims": ["NH왈츠회전예금 II는 4회전기간부터 트리플 회전 우대이율 0.1%p가 적용된다."],
        "author": "codex",
    },
    {
        "claim_id": "p028_c02",
        "product_id": "p028",
        "source_field": "spcl_cnd",
        "label": "UNSUPPORTED",
        "error_type": "term_error",
        "error_match": ["1회전기간부터"],
        "reasoning_type": ["temporal_scope"],
        "insufficient_source": None,
        "instruction": "트리플 회전 우대이율 0.1%p의 적용 시작 시점을 4회전기간부터가 아닌 1회전기간부터로 변경.",
        "answer_text": "NH왈츠회전예금 II는 1회전기간부터 트리플 회전 우대이율 0.1%p가 적용된다.",
        "claims": ["NH왈츠회전예금 II는 1회전기간부터 트리플 회전 우대이율 0.1%p가 적용된다."],
        "author": "codex",
    },
    {
        "claim_id": "p032_c01",
        "product_id": "p032",
        "source_field": "options_12m_base_rate",
        "label": "SUPPORTED",
        "error_type": None,
        "error_match": [],
        "reasoning_type": ["numeric_threshold"],
        "insufficient_source": None,
        "instruction": "하나의정기예금의 12개월 기본금리가 2.3%라는 사실을 그대로 서술.",
        "answer_text": "하나의정기예금의 12개월 기본금리는 2.3%이다.",
        "claims": ["하나의정기예금의 12개월 기본금리는 2.3%이다."],
        "author": "codex",
    },
    {
        "claim_id": "p032_c02",
        "product_id": "p032",
        "source_field": "options_12m_base_rate",
        "label": "UNSUPPORTED",
        "error_type": "base_vs_max_rate",
        "error_match": ["3.2%"],
        "reasoning_type": ["numeric_threshold"],
        "insufficient_source": None,
        "instruction": "하나의정기예금의 실제 12개월 최고금리 3.2%를 기본금리인 것처럼 서술.",
        "answer_text": "하나의정기예금의 12개월 기본금리는 3.2%이다.",
        "claims": ["하나의정기예금의 12개월 기본금리는 3.2%이다."],
        "author": "codex",
    },
    {
        "claim_id": "p037_c01",
        "product_id": "p037",
        "source_field": "options_12m_base_rate",
        "label": "SUPPORTED",
        "error_type": None,
        "error_match": [],
        "reasoning_type": ["numeric_threshold"],
        "insufficient_source": None,
        "instruction": "카카오뱅크 정기예금의 12개월 기본금리가 3.6%라는 사실을 그대로 서술한다.",
        "answer_text": "카카오뱅크 정기예금의 12개월 기본금리는 3.6%이다.",
        "claims": ["카카오뱅크 정기예금의 12개월 기본금리는 3.6%이다."],
        "author": "codex",
    },
    {
        "claim_id": "p037_c02",
        "product_id": "p037",
        "source_field": "options_12m_base_rate",
        "label": "UNSUPPORTED",
        "error_type": "numeric_error",
        "error_match": ["4.1%"],
        "reasoning_type": ["numeric_threshold"],
        "insufficient_source": None,
        "instruction": "카카오뱅크 정기예금의 실제 정보에서 유래하지 않은 4.1%를 12개월 기본금리로 서술한다.",
        "answer_text": "카카오뱅크 정기예금의 12개월 기본금리는 4.1%이다.",
        "claims": ["카카오뱅크 정기예금의 12개월 기본금리는 4.1%이다."],
        "author": "codex",
    },
    {
        "claim_id": "p018_c02",
        "product_id": "p018",
        "source_field": "mtrt_int",
        "label": "SUPPORTED",
        "error_type": None,
        "error_match": [],
        "reasoning_type": ["temporal_scope"],
        "insufficient_source": None,
        "instruction": "BNK더조은정기예금은 만기 후 1개월 이내에 일반정기예금 기본이율의 50%가 적용된다는 사실을 그대로 서술한다.",
        "answer_text": "BNK더조은정기예금은 만기 후 1개월 이내에 일반정기예금 기본이율의 50%가 적용된다.",
        "claims": ["BNK더조은정기예금은 만기 후 1개월 이내에 일반정기예금 기본이율의 50%가 적용된다."],
        "author": "codex",
    },
    {
        "claim_id": "p018_c03",
        "product_id": "p018",
        "source_field": "mtrt_int",
        "label": "UNSUPPORTED",
        "error_type": "boundary_condition_error",
        "error_match": ["20%"],
        "reasoning_type": ["temporal_scope"],
        "insufficient_source": None,
        "instruction": "만기 후 1개월 초과 구간의 20%를 만기 후 1개월 이내 구간에 잘못 적용하여 서술한다.",
        "answer_text": "BNK더조은정기예금은 만기 후 1개월 이내에 일반정기예금 기본이율의 20%가 적용된다.",
        "claims": ["BNK더조은정기예금은 만기 후 1개월 이내에 일반정기예금 기본이율의 20%가 적용된다."],
        "author": "codex",
    },
    {
        "claim_id": "p002_c06",
        "product_id": "p002",
        "source_field": "mtrt_int",
        "label": "SUPPORTED",
        "error_type": None,
        "error_match": [],
        "reasoning_type": ["temporal_scope"],
        "insufficient_source": None,
        "instruction": "e-그린세이브예금은 만기 후 1개월 초과 1년 이내에 약정이율의 30%가 적용된다는 사실을 그대로 서술한다.",
        "answer_text": "e-그린세이브예금은 만기 후 1개월 초과 1년 이내에 약정이율의 30%가 적용된다.",
        "claims": ["e-그린세이브예금은 만기 후 1개월 초과 1년 이내에 약정이율의 30%가 적용된다."],
        "author": "codex",
    },
    {
        "claim_id": "p002_c07",
        "product_id": "p002",
        "source_field": "mtrt_int",
        "label": "UNSUPPORTED",
        "error_type": "term_error",
        "error_match": ["1년 초과에 약정이율의 30%"],
        "reasoning_type": ["temporal_scope"],
        "insufficient_source": None,
        "instruction": "만기 후 1개월 초과 1년 이내 구간의 30%를 만기 후 1년 초과 구간에 잘못 적용하여 서술한다.",
        "answer_text": "e-그린세이브예금은 만기 후 1년 초과에 약정이율의 30%가 적용된다.",
        "claims": ["e-그린세이브예금은 만기 후 1년 초과에 약정이율의 30%가 적용된다."],
        "author": "codex",
    },
    {
        "claim_id": "p022_c02",
        "product_id": "p022",
        "source_field": "options_24m_base_rate",
        "label": "SUPPORTED",
        "error_type": None,
        "error_match": [],
        "reasoning_type": ["numeric_threshold"],
        "insufficient_source": None,
        "instruction": "IBK더굴리기통장(실세금리정기예금)의 24개월 기본금리가 3.24%라는 사실을 그대로 서술한다.",
        "answer_text": "IBK더굴리기통장(실세금리정기예금)의 24개월 기본금리는 3.24%이다.",
        "claims": ["IBK더굴리기통장(실세금리정기예금)의 24개월 기본금리는 3.24%이다."],
        "author": "codex",
    },
    {
        "claim_id": "p022_c03",
        "product_id": "p022",
        "source_field": "options_24m_base_rate",
        "label": "UNSUPPORTED",
        "error_type": "numeric_error",
        "error_match": ["2.8%"],
        "reasoning_type": ["numeric_threshold"],
        "insufficient_source": None,
        "instruction": "IBK더굴리기통장(실세금리정기예금)의 실제 정보에서 유래하지 않은 2.8%를 24개월 기본금리로 서술한다.",
        "answer_text": "IBK더굴리기통장(실세금리정기예금)의 24개월 기본금리는 2.8%이다.",
        "claims": ["IBK더굴리기통장(실세금리정기예금)의 24개월 기본금리는 2.8%이다."],
        "author": "codex",
    },
    {
        "claim_id": "p033_c01",
        "product_id": "p033",
        "source_field": "mtrt_int",
        "label": "SUPPORTED",
        "error_type": None,
        "error_match": [],
        "reasoning_type": ["temporal_scope"],
        "insufficient_source": None,
        "instruction": "코드K 정기예금은 만기 후 1개월 초과 6개월 이내에 만기시점 기본금리의 30%가 적용된다는 사실을 그대로 서술한다.",
        "answer_text": "코드K 정기예금은 만기 후 1개월 초과 6개월 이내에 만기시점 기본금리의 30%가 적용된다.",
        "claims": ["코드K 정기예금은 만기 후 1개월 초과 6개월 이내에 만기시점 기본금리의 30%가 적용된다."],
        "author": "codex",
    },
    {
        "claim_id": "p033_c02",
        "product_id": "p033",
        "source_field": "mtrt_int",
        "label": "UNSUPPORTED",
        "error_type": "boundary_condition_error",
        "error_match": ["6개월 초과에 만기시점 기본금리의 30%"],
        "reasoning_type": ["temporal_scope"],
        "insufficient_source": None,
        "instruction": "만기 후 1개월 초과 6개월 이내 구간의 30%를 만기 후 6개월 초과 구간에 잘못 적용하여 서술한다.",
        "answer_text": "코드K 정기예금은 만기 후 6개월 초과에 만기시점 기본금리의 30%가 적용된다.",
        "claims": ["코드K 정기예금은 만기 후 6개월 초과에 만기시점 기본금리의 30%가 적용된다."],
        "author": "codex",
    },
]
