"""Issue #23 -- Test-stage scenarios authored directly by Claude Code (no API call).

Same scenario schema as generate_synthetic_answers.py's SCENARIOS, plus
`answer_text` and `claims` written by hand instead of generated by an API
call, and `author` for provenance. `evidence_override` is used only by the
evidence_mismatch scenario, where the evidence intentionally does NOT come
from resolve_evidence's normal product/field lookup (see its docstring below).

Products used here were never touched in Smoke/Pilot (data/smoke/claim_dataset.json):
p004, p008, p010, p013 (new field: mtrt_int, Pilot used spcl_cnd/options_all),
p017, p019, p021 (new field: spcl_cnd, Pilot used mtrt_int), p023, p024.
"""

SCENARIOS_CLAUDE = [
    # --- p004 iM스마트예금 -- spcl_cnd any_of (1가지 이상 요건) + condition_reversal ---
    {
        "claim_id": "p004_c01",
        "product_id": "p004",
        "source_field": "spcl_cnd",
        "label": "SUPPORTED",
        "error_type": None,
        "error_match": [],
        "reasoning_type": ["any_of"],
        "insufficient_source": None,
        "instruction": "가입일로부터 3개월 이내 주택청약종합저축 보유 또는 카드 결제실적 보유 중 하나만 충족해도 0.25%p 우대라는 조건(any_of)을 그대로 서술.",
        "answer_text": "iM스마트예금은 가입일로부터 3개월 이내에 당행 주택청약종합저축 보유 또는 신용(체크)카드 결제실적 보유 중 하나만 충족해도 연 0.25%p의 우대금리가 적용된다.",
        "claims": ["iM스마트예금은 가입일로부터 3개월 이내에 당행 주택청약종합저축 보유 또는 신용(체크)카드 결제실적 보유 중 하나만 충족해도 연 0.25%p의 우대금리가 적용된다."],
        "author": "claude",
    },
    {
        "claim_id": "p004_c02",
        "product_id": "p004",
        "source_field": "spcl_cnd",
        "label": "UNSUPPORTED",
        "error_type": "condition_reversal",
        "error_match": ["모두 충족"],
        "reasoning_type": ["any_of"],
        "insufficient_source": None,
        "instruction": "any_of(1가지 이상)를 all_of(둘 다 충족)로 반전.",
        "answer_text": "iM스마트예금은 가입일로부터 3개월 이내에 당행 주택청약종합저축 보유와 신용(체크)카드 결제실적 보유를 모두 충족해야 연 0.25%p의 우대금리가 적용된다.",
        "claims": ["iM스마트예금은 가입일로부터 3개월 이내에 당행 주택청약종합저축 보유와 신용(체크)카드 결제실적 보유를 모두 충족해야 연 0.25%p의 우대금리가 적용된다."],
        "author": "claude",
    },
    # --- p008 미즈월복리정기예금 -- 요구불평잔 구간(300만원=0.1%, 500만원=0.2%) + boundary_condition_error ---
    {
        "claim_id": "p008_c01",
        "product_id": "p008",
        "source_field": "spcl_cnd",
        "label": "SUPPORTED",
        "error_type": None,
        "error_match": [],
        "reasoning_type": ["numeric_threshold"],
        "insufficient_source": None,
        "instruction": "요구불평잔 500만원 이상 시 0.2% 우대 조건을 그대로 서술.",
        "answer_text": "미즈월복리정기예금은 요구불평잔이 500만원 이상이면 연 0.2%의 우대금리를 받을 수 있다.",
        "claims": ["미즈월복리정기예금은 요구불평잔이 500만원 이상이면 연 0.2%의 우대금리를 받을 수 있다."],
        "author": "claude",
    },
    {
        "claim_id": "p008_c02",
        "product_id": "p008",
        "source_field": "spcl_cnd",
        "label": "UNSUPPORTED",
        "error_type": "boundary_condition_error",
        "error_match": ["300만원 이상이면 연 0.2%"],
        "reasoning_type": ["numeric_threshold"],
        "insufficient_source": None,
        "instruction": "낮은 구간(300만원=0.1%)에 높은 구간의 우대율(0.2%)을 붙임.",
        "answer_text": "미즈월복리정기예금은 요구불평잔이 300만원 이상이면 연 0.2%의 우대금리를 받을 수 있다.",
        "claims": ["미즈월복리정기예금은 요구불평잔이 300만원 이상이면 연 0.2%의 우대금리를 받을 수 있다."],
        "author": "claude",
    },
    # --- p010 굿스타트예금 -- 첫예금거래 자격조건(이력 없어야 함) + eligibility_error(반전) ---
    {
        "claim_id": "p010_c01",
        "product_id": "p010",
        "source_field": "spcl_cnd",
        "label": "SUPPORTED",
        "error_type": None,
        "error_match": [],
        "reasoning_type": ["temporal_scope"],
        "insufficient_source": None,
        "instruction": "최근 1년간 정기예금 신규/해지 이력이 '없어야' 0.4% 우대라는 조건을 그대로 서술.",
        "answer_text": "굿스타트예금은 최근 1년 동안 정기예금 계좌의 신규 또는 해지 이력이 없는 경우 연 0.4%의 우대금리를 받을 수 있다.",
        "claims": ["굿스타트예금은 최근 1년 동안 정기예금 계좌의 신규 또는 해지 이력이 없는 경우 연 0.4%의 우대금리를 받을 수 있다."],
        "author": "claude",
    },
    {
        "claim_id": "p010_c02",
        "product_id": "p010",
        "source_field": "spcl_cnd",
        "label": "UNSUPPORTED",
        "error_type": "eligibility_error",
        "error_match": ["이력이 있는"],
        "reasoning_type": ["temporal_scope"],
        "insufficient_source": None,
        "instruction": "자격조건을 반대로 뒤집음 (이력이 없어야 하는데 있어야 하는 것처럼).",
        "answer_text": "굿스타트예금은 최근 1년 동안 정기예금 계좌를 신규하거나 해지한 이력이 있는 경우에 연 0.4%의 우대금리를 받을 수 있다.",
        "claims": ["굿스타트예금은 최근 1년 동안 정기예금 계좌를 신규하거나 해지한 이력이 있는 경우에 연 0.4%의 우대금리를 받을 수 있다."],
        "author": "claude",
    },
    # --- p017 내맘 쏙 정기예금 -- SUPPORTED faithful + evidence_mismatch(cross-field) ---
    {
        "claim_id": "p017_c01",
        "product_id": "p017",
        "source_field": "spcl_cnd",
        "label": "SUPPORTED",
        "error_type": None,
        "error_match": [],
        "reasoning_type": [],
        "insufficient_source": None,
        "instruction": "마케팅동의고객 0.10% 우대 조건을 그대로 서술.",
        "answer_text": "내맘 쏙 정기예금은 마케팅동의를 한 고객에게 연 0.10%의 우대금리를 제공한다.",
        "claims": ["내맘 쏙 정기예금은 마케팅동의를 한 고객에게 연 0.10%의 우대금리를 제공한다."],
        "author": "claude",
    },
    {
        # evidence_mismatch (cross-field flavor): the claim states a TRUE fact
        # about p017's mtrt_int field, but the evidence handed to the
        # Verifier is p017's spcl_cnd field only -- simulating a retrieval
        # step that fetched the wrong field for this question. Gold is
        # INSUFFICIENT (not UNSUPPORTED) because the given evidence doesn't
        # address maturity-interest at all, it doesn't conflict with it.
        "claim_id": "p017_c02",
        "product_id": "p017",
        "source_field": "spcl_cnd",
        "label": "INSUFFICIENT",
        "error_type": "evidence_mismatch",
        "error_match": ["만기 후"],
        "reasoning_type": ["cross_field_mismatch"],
        "insufficient_source": "wrong_field_retrieved",
        "instruction": (
            "claim은 p017의 mtrt_int(만기후 1개월 초과 시 연 0.01%)에 대한 사실이지만, "
            "evidence로는 p017의 spcl_cnd만 준다 -- RAG가 엉뚱한 필드를 가져온 상황을 시뮬레이션."
        ),
        "answer_text": "내맘 쏙 정기예금은 만기 후 1개월을 초과하면 연 0.01%의 이자율이 적용된다.",
        "claims": ["내맘 쏙 정기예금은 만기 후 1개월을 초과하면 연 0.01%의 이자율이 적용된다."],
        "author": "claude",
    },
    # --- p019 The든든예금(시즌2) -- 조건별 이벤트금리 + conditional_benefit_generalization ---
    {
        "claim_id": "p019_c01",
        "product_id": "p019",
        "source_field": "spcl_cnd",
        "label": "SUPPORTED",
        "error_type": None,
        "error_match": [],
        "reasoning_type": ["all_of"],
        "insufficient_source": None,
        "instruction": "비대면 가입 + 12개월 만기 조건에서만 최대 1.15% 이벤트금리라는 조건을 그대로 서술.",
        "answer_text": "The든든예금(시즌2)은 비대면으로 가입하고 12개월 만기를 선택하면 최대 1.15%의 이벤트금리(비대면금리)가 적용된다.",
        "claims": ["The든든예금(시즌2)은 비대면으로 가입하고 12개월 만기를 선택하면 최대 1.15%의 이벤트금리(비대면금리)가 적용된다."],
        "author": "claude",
    },
    {
        "claim_id": "p019_c02",
        "product_id": "p019",
        "source_field": "spcl_cnd",
        "label": "UNSUPPORTED",
        "error_type": "conditional_benefit_generalization",
        "error_match": ["만기와 무관"],
        "reasoning_type": ["all_of"],
        "insufficient_source": None,
        "instruction": "비대면+12개월 특정 조건을 무시하고 모든 만기에 항상 적용되는 것처럼 일반화.",
        "answer_text": "The든든예금(시즌2)에 가입하면 만기와 무관하게 항상 최대 1.15%의 이벤트금리가 적용된다.",
        "claims": ["The든든예금(시즌2)에 가입하면 만기와 무관하게 항상 최대 1.15%의 이벤트금리가 적용된다."],
        "author": "claude",
    },
    # --- p021 IBK평생한가족통장 -- spcl_cnd(고객별 우대) + conditional_benefit_generalization ---
    {
        "claim_id": "p021_c02",
        "product_id": "p021",
        "source_field": "spcl_cnd",
        "label": "SUPPORTED",
        "error_type": None,
        "error_match": [],
        "reasoning_type": [],
        "insufficient_source": None,
        "instruction": "최초신규고객에게만 0.05%p 우대라는 조건을 그대로 서술 (claim_id는 Pilot의 mtrt_int 기반 p021_c01과 구분).",
        "answer_text": "IBK평생한가족통장은 최초신규고객에 해당하면 연 0.05%p의 우대금리를 받을 수 있다.",
        "claims": ["IBK평생한가족통장은 최초신규고객에 해당하면 연 0.05%p의 우대금리를 받을 수 있다."],
        "author": "claude",
    },
    {
        "claim_id": "p021_c03",
        "product_id": "p021",
        "source_field": "spcl_cnd",
        "label": "UNSUPPORTED",
        "error_type": "conditional_benefit_generalization",
        "error_match": ["조건과 무관"],
        "reasoning_type": [],
        "insufficient_source": None,
        "instruction": "고객별 세부 조건(신규/재예치/장기거래/주거래)을 무시하고 누구나 최고 우대금리를 받는 것처럼 일반화.",
        "answer_text": "IBK평생한가족통장에 가입하는 모든 고객은 조건과 무관하게 최고 연 0.20%p의 우대금리를 받을 수 있다.",
        "claims": ["IBK평생한가족통장에 가입하는 모든 고객은 조건과 무관하게 최고 연 0.20%p의 우대금리를 받을 수 있다."],
        "author": "claude",
    },
    # --- p023 IBK굴리기통장 -- mtrt_int 3구간 + term_error(구간 뒤바꿈) ---
    {
        "claim_id": "p023_c01",
        "product_id": "p023",
        "source_field": "mtrt_int",
        "label": "SUPPORTED",
        "error_type": None,
        "error_match": [],
        "reasoning_type": ["temporal_scope"],
        "insufficient_source": None,
        "instruction": "만기 후 1개월 초과 6개월 이내 구간의 30% 적용을 그대로 서술.",
        "answer_text": "IBK굴리기통장은 만기 후 1개월 초과 6개월 이내 기간에는 계약기간별 고시금리의 30%가 적용된다.",
        "claims": ["IBK굴리기통장은 만기 후 1개월 초과 6개월 이내 기간에는 계약기간별 고시금리의 30%가 적용된다."],
        "author": "claude",
    },
    {
        "claim_id": "p023_c02",
        "product_id": "p023",
        "source_field": "mtrt_int",
        "label": "UNSUPPORTED",
        "error_type": "term_error",
        "error_match": ["20%가 적용된다"],
        "reasoning_type": ["temporal_scope"],
        "insufficient_source": None,
        "instruction": "1개월초과~6개월이내 구간(실제 30%)에 그 다음 구간의 값(20%)을 붙임.",
        "answer_text": "IBK굴리기통장은 만기 후 1개월 초과 6개월 이내 기간에는 계약기간별 고시금리의 20%가 적용된다.",
        "claims": ["IBK굴리기통장은 만기 후 1개월 초과 6개월 이내 기간에는 계약기간별 고시금리의 20%가 적용된다."],
        "author": "claude",
    },
    # --- p024 KDB 정기예금 -- spcl_cnd=None -> 자연결측 INSUFFICIENT ---
    {
        "claim_id": "p024_c01",
        "product_id": "p024",
        "source_field": "spcl_cnd",
        "label": "INSUFFICIENT",
        "error_type": "missing_information",
        "error_match": ["자동이체"],
        "reasoning_type": [],
        "insufficient_source": "natural_missing",
        "instruction": "이 상품은 우대조건(spcl_cnd) 정보 자체가 없다. 그런데도 자동이체 등록 시 우대금리를 받는다고 서술.",
        "answer_text": "KDB 정기예금은 자동이체를 등록하면 우대금리를 추가로 받을 수 있다.",
        "claims": ["KDB 정기예금은 자동이체를 등록하면 우대금리를 추가로 받을 수 있다."],
        "author": "claude",
    },
    # --- p013 J정기예금(만기지급식) -- mtrt_int 신규 각도(Pilot은 spcl_cnd/options_all 사용) + term_error ---
    {
        "claim_id": "p013_c04",
        "product_id": "p013",
        "source_field": "mtrt_int",
        "label": "SUPPORTED",
        "error_type": None,
        "error_match": [],
        "reasoning_type": ["temporal_scope"],
        "insufficient_source": None,
        "instruction": "만기 후 1개월 초과 3개월 이내 구간 25% 적용을 그대로 서술 (claim_id는 Pilot의 p013_c01~03과 구분).",
        "answer_text": "J정기예금(만기지급식)은 만기 후 1개월 초과 3개월 이내에는 일반정기예금 기본이자율의 25%가 적용된다.",
        "claims": ["J정기예금(만기지급식)은 만기 후 1개월 초과 3개월 이내에는 일반정기예금 기본이자율의 25%가 적용된다."],
        "author": "claude",
    },
    {
        "claim_id": "p013_c05",
        "product_id": "p013",
        "source_field": "mtrt_int",
        "label": "UNSUPPORTED",
        "error_type": "term_error",
        "error_match": ["3개월 초과 시 일반정기예금 기본이자율의 25%"],
        "reasoning_type": ["temporal_scope"],
        "insufficient_source": None,
        "instruction": "3개월초과 구간(실제 0.1% 고정)에 그 이전 구간의 값(25%)을 붙임.",
        "answer_text": "J정기예금(만기지급식)은 만기 후 3개월 초과 시 일반정기예금 기본이자율의 25%가 적용된다.",
        "claims": ["J정기예금(만기지급식)은 만기 후 3개월 초과 시 일반정기예금 기본이자율의 25%가 적용된다."],
        "author": "claude",
    },
    # --- p038 토스뱅크 -- evidence_mismatch(cross-product numeric conflict) ---
    {
        # evidence_mismatch (numeric-conflict flavor): the claim's number
        # (2.3%) is a REAL rate -- it's p032's actual 12mo base rate -- but
        # is paired with p038's evidence, whose 12mo base rate is 3.6%.
        # Unlike a plain numeric_error (an arbitrary made-up number), this
        # simulates a retrieval mixup where a real number from the wrong
        # product's document ends up next to this product's evidence. The
        # Verifier-facing artifact is mechanically similar to numeric_error,
        # but the generation story is distinct enough to warrant its own
        # error_type for failure_analysis.py's breakdown.
        "claim_id": "p038_c01",
        "product_id": "p038",
        "source_field": "options_12m_base_rate",
        "label": "UNSUPPORTED",
        "error_type": "evidence_mismatch",
        "error_match": ["2.3%"],
        "reasoning_type": ["numeric_threshold"],
        "insufficient_source": None,
        "instruction": "12개월 기본금리로 실제로는 다른 상품(p032)의 진짜 수치(2.3%)를 붙임 -- evidence(p038, 3.6%)와 직접 충돌.",
        "answer_text": "12개월 정기예금 기본금리는 연 2.3%이다.",
        "claims": ["12개월 정기예금 기본금리는 연 2.3%이다."],
        "author": "claude",
    },
]
